# Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
#
# Theme Elements & Colors for Hyprland.

# Elements
$hypr_border_size = 1
$hypr_gaps_in = 4
$hypr_gaps_out = 8
$hypr_rounding = 1

# Colors
$gradient_angle = 45deg
# $active_border_col_1 = 0xFF89B4FA
$active_border_col_1 = 0xFFFB5012
# $active_border_col_2 = 0xFFF28FAD
$active_border_col_2 = 0xFFB53203
# $inactive_border_col_1 = 0xFF313244
$inactive_border_col_1 = 0xFF18181B
$inactive_border_col_2 = 0xFF0A0A0B
$active_shadow_col = 0x66000000
$inactive_shadow_col = 0x66000000
$group_border_col = 0xFFFB5012
$group_border_active_col = 0xFFB53203
